Revert "Make memset function static"
memset should not be static, since it's needed by the C startup code and
leaving this static without installing newlib results in a link failure:

    aarch64-linux-gnu-ld: main.o: in function `main':
    main.c:(.text.startup+0x22c): undefined reference to `memset'

I don't really want there to be any external dependencies other than gcc
and binutils, so let's make memset "not static" again.

This reverts commit 9c83fce07e78b5c52d37d71cfde848ea0b476481.